# Generated by Django 5.2.14 on 2026-08-09 23:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rastreador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=100, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('data_vinculacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rastreador', to='pets.pet')),
            ],
            options={
                'verbose_name': 'Rastreador',
                'verbose_name_plural': 'Rastreadores',
            },
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('rastreador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='locator.rastreador')),
            ],
            options={
                'verbose_name': 'Localizacao',
                'verbose_name_plural': 'Localizacoes',
                'ordering': ['-timestamp'],
            },
        ),
    ]
