# Generated by Django 5.2.14 on 2026-08-09 23:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('lote', models.CharField(max_length=50)),
                ('data_aplicacao', models.DateField()),
                ('data_reforco', models.DateField(blank=True, null=True)),
                ('veterinario', models.CharField(max_length=100)),
                ('clinica', models.CharField(max_length=100)),
                ('observacoes', models.TextField(blank=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to='pets.pet')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacina',
                'verbose_name_plural': 'Vacinas',
            },
        ),
    ]
